#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          moteur,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//------------- Main -------------//
#include "header.h"
#include "fix.c"
#include "mobile.c"

task interface(){

	eraseDisplay();
	displayCenteredTextLine(4, "Boussole");
	displayTextLine(6, "Bouton gauche: Mode Fixe");
	displayTextLine(8, "Bouton droite: Mode Mobile");

	while(getButtonPress(buttonLeft)==0 && getButtonPress(buttonRight)==0){}

	if(getButtonPress(buttonLeft)==1){
		while(getButtonPress(buttonLeft)==1){}

		initialize();
		startTask(keepHeadingPID);
	}
	else if(getButtonPress(buttonRight)==1){
		while(getButtonPress(buttonRight)==1){}

		initialize();
		startTask(keepHeadingPID2);
	}
}

void initialize() {
	eraseDisplay();
	displayCenteredTextLine(4, "Initialization");
	displayTextLine(6, "Btn Gauche: Tourner a gauche");
	displayTextLine(7, "Btn Droite: Tourner a droite");
	displayTextLine(8, "Btn Haut  : Continuer");

	int speed=20;

	while(getButtonPress(buttonUp)==0) {

		setMotorSpeed(moteur, 0);

		if(getButtonPress(buttonLeft)==1){

			setMotorSpeed(moteur, speed);
			while(getButtonPress(buttonLeft)==1){}

		}
		else if(getButtonPress(buttonRight)==1){

			setMotorSpeed(moteur, -speed);
			while(getButtonPress(buttonRight)==1){}

		}

	}

	while(getButtonPress(buttonUp)==1) {}
	setMotorSpeed(moteur, 0);
}

void stopFix() {
	stopTask(keepHeadingPID);
	stopTask(watchButtons);
	stopTask(IHM);
}

void stopMobile() {
	stopTask(keepHeadingPID2);
	stopTask(watchButtons2);
	stopTask(IHM2);
}

task main() {
	startTask(interface);
	while(true){
		// A tout moment, si on click le bouton du center, on va lancer le menu principal
		if(getButtonPress(buttonEnter) == 1){
			stopFix();
			stopMobile();
			setMotorSpeed(moteur, 0);
			startTask(interface);
			} else if(getTouchValue(touchSensor) == 1){
			stopAllTasks();
		}
	}
}
