#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S4,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorA,          moteur,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//------------- Main -------------//
#include "header.h"
#include "fix.c"
#include "mobile.c"

// Interface utilisateur
task interface() {

	eraseDisplay();
	displayCenteredTextLine(4, "Boussole");
	displayTextLine(6, "Bouton gauche: Mode Fixe");
	displayTextLine(8, "Bouton droite: Mode Mobile");
	displayTextLine(14, "Touch sensor: Quitter");

    // Tant qu'on a pas fait un choix (gauche -> mode fixe, droite -> mode mobile)
	while(!getButtonPress(buttonLeft) && !getButtonPress(buttonRight)) {}

	if(getButtonPress(buttonLeft)){
		while(getButtonPress(buttonLeft)) {} // Tant qu'on a pas relache le bouton
		initialize();
		startFix();
	}
	else if(getButtonPress(buttonRight)){
		while(getButtonPress(buttonRight)) {}
		initialize();
		startMobile();
	}
}

// Fonction d'initialization, pour eviter les problemes de cable liee au gyro
void initialize() {
	eraseDisplay();
	displayCenteredTextLine(4, "Initialization");
	displayTextLine(6, "Btn Gauche: Tourner a gauche");
	displayTextLine(7, "Btn Droite: Tourner a droite");
	displayTextLine(8, "Btn Haut  : Continuer");

	int speed = 20;

	while(!getButtonPress(buttonUp)) {
		if(getButtonPress(buttonLeft)) {
			setMotorSpeed(moteur, speed);
			while(getButtonPress(buttonLeft)) {} // Tant qu'on a pas relache le bouton
		}
		else if(getButtonPress(buttonRight)) {
			setMotorSpeed(moteur, -speed);
			while(getButtonPress(buttonRight)) {}
        }
		setMotorSpeed(moteur, 0);
		delay(100);
	}

	setMotorSpeed(moteur, 0);
	delay(300);
}

void startFix() {
	semaphoreInitialize(semConsigne);
	startTask(watchButtons);
	startTask(keepHeadingPID);
	startTask(IHM);
}

void startMobile() {
	semaphoreInitialize(semConsigne2);
	resetGyro(gyro);
	startTask(keepHeadingPID2);
	// startTask(watchButtons2); // Inutil pour la boussole (voir l'implementation dans mobile.c pour plus d'info)
	startTask(IHM2);
}

void stopFix() {
	stopTask(watchButtons);
	stopTask(keepHeadingPID);
	stopTask(IHM);
}

void stopMobile() {
	stopTask(keepHeadingPID2);
	//stopTask(watchButtons2); // On ne lance pas la tache -> on l'arrette pas
	stopTask(IHM2);
}

// Tache principal
task main() {
	startTask(interface);
	while(true){
		// A tout moment, si on click le bouton du center, on va lancer le menu principal
		if(getButtonPress(buttonEnter)){
			stopFix();
			stopMobile();
			setMotorSpeed(moteur, 0);
			startTask(interface);
			} else if(getTouchValue(touchSensor)){ // Si on appui sur le capteur de contact, on arrette le programme
			stopAllTasks();
		}
	}
}
